### ISSUE TITLE
7z file not encrypted

### ISSUE THREAD

**Issue by carlosmejia85** [jbdemonte/node-p7zip#3]
Hello, running your demo is working fine, but i wanted to generate a password protected file and i add this parameter on switch 

.add('test.7z', '*.js', 'p123456789')

but i don't know if this is correct. 

But on your source code i saw that args are being added at the end, but for encryption that parameter does not have to be added at the end. 

Example: 
 7za a -pmy_password archive.7z  dir1

that is why i think it is not working. 

Could you please check that? 

Best Regards,

**Comment by jbdemonte** [comment]
notice, in the v3, you'll have to set the "-" in your switches

thanks for the report
