### ISSUE TITLE
Win10 installation failed

### ISSUE THREAD

**Issue by carlosmejia85** [jbdemonte/node-p7zip#4]
This is the error i get: 

C:\Users\cmejia\Desktop\7zipDemo>npm install --save p7zip
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> p7zip@2.3.0 install C:\Users\cmejia\Desktop\7zipDemo\node_modules\p7zip
> node scripts/install.js

Downloading https://github.com/jbdemonte/p7zip/archive/16.02.zip
Decompress 16.02.zip
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn make ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\cmejia\Desktop\7zipDemo\package.json'
npm WARN 7zipDemo No description
npm WARN 7zipDemo No repository field.
npm WARN 7zipDemo No README data
npm WARN 7zipDemo No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "p7zip"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! p7zip@2.3.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the p7zip@2.3.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the p7zip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs p7zip
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls p7zip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cmejia\Desktop\7zipDemo\npm-debug.log

**Comment by jbdemonte** [comment]
Normal, p7zip is a port of a win version, more information on [this page](http://p7zip.sourceforge.net/)

It does not target windows
